name: Build and push Docker image to ECR

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      role_to_assume:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main project
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # 5.2.0
        with:
          distribution: 'temurin'
          java-version-file: .java-version
          cache: 'maven'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # 6.2.0
        with:
          role-to-assume: ${{ inputs.role_to_assume }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@fa648b43de3d4d023bcb3f89ed6940096949c419 # 2.1.5

      - name: Build and push container image
        run: |
          ./mvnw -e -B deploy \
            -Dpackaging=docker \
            -Djib.to.image="${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:${GITHUB_REF_NAME}"
